[
    {
        "Question_id":53991961,
        "Question_title":"File not found even after adding the file inside docker",
        "Question_body":"<p>I have written a docker file which adds my python script inside the container:\n<code>ADD test_pclean.py \/test_pclean.py<\/code><\/p>\n\n<p>My directory structure is:<\/p>\n\n<pre><code>.\n\u251c\u2500\u2500 Dockerfile\n\u251c\u2500\u2500 README.md\n\u251c\u2500\u2500 pipeline.json\n\u2514\u2500\u2500 test_pclean.py\n<\/code><\/pre>\n\n<p>My json file which acts as a configuration file for creating a pipeline in Pachyderm is as follows:<\/p>\n\n<pre><code>{\n    \"pipeline\": {\n        \"name\": \"mopng-beneficiary-v2\"\n    },\n    \"transform\": {\n        \"cmd\": [\"python3\", \"\/test_pclean.py\"],\n        \"image\": \"avisrivastava254084\/mopng-beneficiary-v2-image-7\"\n    },\n    \"input\": {\n        \"atom\": {\n            \"repo\": \"mopng_beneficiary_v2\",\n            \"glob\": \"\/*\"\n        }\n    }\n}\n<\/code><\/pre>\n\n<p>Even though I have copied the official documentation's example, I am facing an error:\n<code>python3: can't open file '\/test_pclean.py': [Errno 2] No such file or directory<\/code><\/p>\n\n<p>My dockerfile is:<\/p>\n\n<pre><code>FROM    debian:stretch\n\n# Install opencv and matplotlib.\nRUN apt-get update \\\n    &amp;&amp; apt-get upgrade -y \\\n    &amp;&amp; apt-get install -y unzip wget build-essential \\\n        cmake git pkg-config libswscale-dev \\\n    &amp;&amp; apt-get clean \\\n    &amp;&amp; rm -rf \/var\/lib\/apt\n\nRUN apt update\nRUN apt-get -y install python3-pip\nRUN pip3 install matplotlib\nRUN pip3 install pandas\n\nADD test_pclean.py \/test_pclean.py\nENTRYPOINT [ \"\/bin\/bash\/\" ]\n<\/code><\/pre>",
        "Question_answer_count":2,
        "Question_comment_count":6,
        "Question_creation_date":"2018-12-31 22:48:53.713 UTC",
        "Question_favorite_count":null,
        "Question_last_edit_date":"2019-01-02 10:06:19.99 UTC",
        "Question_score":0,
        "Question_tags":"python|python-3.x|docker|pachyderm",
        "Question_view_count":430,
        "Owner_creation_date":"2018-07-10 15:06:30.283 UTC",
        "Owner_last_access_date":"2019-02-13 09:38:09.97 UTC",
        "Owner_reputation":903,
        "Owner_up_votes":53,
        "Owner_down_votes":0,
        "Owner_views":144,
        "Answer_body":"<p>I was not changing the commits to my docker images on each build and hence, Kubernetes was using the local docker file that it had(w\/o tags and commits, it doesn't acknowledge any change). Once I started using commit with each build, Kubernetes started downloading the intended docker image.<\/p>",
        "Answer_comment_count":0.0,
        "Answer_creation_date":"2019-01-17 10:20:58.433 UTC",
        "Answer_score":0.0,
        "Owner_location":"delhi",
        "Answer_last_edit_date":null,
        "Question_link":"https:\/\/stackoverflow.com\/questions\/53991961",
        "Question_exclusive_tag":"Pachyderm"
    },
    {
        "Question_id":67937857,
        "Question_title":"Pachyderm deploy GCP - no such image",
        "Question_body":"<p>I'm deploying Pachyderm on GKE but when I deploy the pipeline (following the <a href=\"https:\/\/docs.pachyderm.com\/latest\/getting_started\/beginner_tutorial\/\" rel=\"nofollow noreferrer\">https:\/\/docs.pachyderm.com\/latest\/getting_started\/beginner_tutorial\/<\/a>) the Pod fails in ImagePullCrashLoopBack giving this error &quot;no such image&quot;.<\/p>\n<p>Here, the output of the command &quot;kubectl get pods&quot;:\n<a href=\"https:\/\/i.stack.imgur.com\/lpvj7.png\" rel=\"nofollow noreferrer\">screenshot<\/a><\/p>\n<p>How can I fix the deployment procedure?<\/p>",
        "Question_answer_count":1,
        "Question_comment_count":1,
        "Question_creation_date":"2021-06-11 13:26:09.943 UTC",
        "Question_favorite_count":null,
        "Question_last_edit_date":null,
        "Question_score":0,
        "Question_tags":"kubernetes|google-cloud-platform|pachyderm",
        "Question_view_count":48,
        "Owner_creation_date":"2014-11-06 09:41:52.943 UTC",
        "Owner_last_access_date":"2022-09-24 19:13:38.297 UTC",
        "Owner_reputation":107,
        "Owner_up_votes":27,
        "Owner_down_votes":0,
        "Owner_views":24,
        "Answer_body":"<p>As mentioned in the Slack channel of Pachyderm community, adding the flag <code>--no-expose-docker-socket<\/code> to the deploy call should solve the issue.<\/p>\n<p><code>pachctl deploy google ${BUCKET_NAME} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --no-expose-docker-socket<\/code><\/p>",
        "Answer_comment_count":1.0,
        "Answer_creation_date":"2021-06-11 13:29:00.677 UTC",
        "Answer_score":1.0,
        "Owner_location":"Milano, Metropolitan City of Milan, Italy",
        "Answer_last_edit_date":null,
        "Question_link":"https:\/\/stackoverflow.com\/questions\/67937857",
        "Question_exclusive_tag":"Pachyderm"
    }
]